In [27]:
# script for plotting all buoy data. 
import pandas as pd
import numpy as np
import cartopy.crs as ccrs
import cartopy.feature as cpf 
import matplotlib.pyplot as plt
import genplots as gp
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
import os
np.set_printoptions(threshold=np.inf)
params = {'legend.fontsize': '16',
         'axes.labelsize': 'x-large',
         'axes.titlesize':'x-large',
         'xtick.labelsize':'16',
         'ytick.labelsize':'16',
         "font.weight":'bold'}
plt.rcParams.update(params)

In [18]:
folder='../Buoy_data_excel/procesd_buoy_loc_data_Lars/BUOY_02.csv'
buoy=os.path.basename(folder)
bname=buoy.split('.')[0]
print(bname.split('_')[1]+'_x')
print()

02_x



In [19]:
folder='../Buoy_data_excel/procesd_buoy_loc_data_Lars'
BD={}
for f in os.listdir(folder):
    if f!='BUOY_06.csv':
        strfile=folder+'/'+f
        buoy=os.path.basename(strfile)
        bname=buoy.split('.')[0]
        xbname=bname.split('_')[1]+'_x'
        ybname=bname.split('_')[1]+'_y'
        D=pd.read_csv(strfile)
        Xib=np.array(D['Lon'])[96:]
        Yib=np.array(D['Lat'])[96:]
#         D.head()
        BD[xbname]= Xib; BD[ybname]=Yib
        print(strfile)

../Buoy_data_excel/procesd_buoy_loc_data_Lars/BUOY_02.csv
../Buoy_data_excel/procesd_buoy_loc_data_Lars/BUOY_03.csv
../Buoy_data_excel/procesd_buoy_loc_data_Lars/BUOY_07.csv
../Buoy_data_excel/procesd_buoy_loc_data_Lars/BUOY_09.csv
../Buoy_data_excel/procesd_buoy_loc_data_Lars/BUOY_12.csv
../Buoy_data_excel/procesd_buoy_loc_data_Lars/BUOY_13.csv
../Buoy_data_excel/procesd_buoy_loc_data_Lars/BUOY_14.csv
../Buoy_data_excel/procesd_buoy_loc_data_Lars/BUOY_16.csv


In [21]:
# print(BD['02_x'],)
Buoys=['02','03','09','07','12','13','14','16']
# for b in Buoys:
#     print (type(b))
#     print(b+'_x')


In [9]:
#Buoy data analysis

D=pd.read_csv('../Buoy_data_excel/procesd_buoy_loc_data_Lars/BUOY_16.csv')
Xib=np.array(D['Lon'])[96:]
Yib=np.array(D['Lat'])[96:]
D.head()

Date(GMT)      Lat      Lon
0  15-3-2014 00:00  79.1288  25.2050
1  15-3-2014 00:15  79.1278  25.2010
2  15-3-2014 00:30  79.1266  25.1970
3  15-3-2014 00:45  79.1254  25.1926
4  15-3-2014 01:00  79.1242  25.1874

In [26]:

fig=plt.figure(figsize=(12, 12), frameon=True)
ax=plt.axes(projection=ccrs.LambertAzimuthalEqualArea(central_longitude=25.0,central_latitude=77.0)) 
# feature=cpf.GSHHSFeature(scale='i',levels=[1],facecolor='#A3A3A3',alpha=1)
ax.set_extent([16,28,74.5,80])
# Define gridline locations and draw the lines using cartopy's built-in gridliner:
# *must* call draw in order to get the axis boundary used to add ticks:
# feature=cpf.GSHHSFeature(scale='i',levels=[1],facecolor='#AAAAAA')
# ax.add_feature(feature) 
# 
colors=['red','green','magenta','darkblue','lime','orange','yellow','olive']
fig.canvas.draw()
xticks = [ 0, 4, 12, 16, 20, 24, 28, 32, 36]
yticks = [72, 74.5, 77, 79.5, 82]
ax.gridlines(xlocs=xticks, ylocs=yticks)
# Label the end-points of the gridlines using the custom tick makers:
ax.xaxis.set_major_formatter(LONGITUDE_FORMATTER) 
ax.yaxis.set_major_formatter(LATITUDE_FORMATTER)
gp.lambert_xticks(ax, xticks)
gp.lambert_yticks(ax, yticks)
i=0;pt=96*1
for b in Buoys:
    # Plotting b-uoy obs and buoy simulated locations
    Xib=BD[b+'_x'];Yib=BD[b+'_y']
    plt.scatter(Xib[pt],Yib[pt],color='black',transform=ccrs.PlateCarree())
    plt.text(Xib[pt],Yib[pt], b, transform=ccrs.PlateCarree(),fontsize=15,fontweight='bold')
#     plt.annotate(b,(Xib[96],Yib[96]),xycoords='Transform')
    plt.plot(Xib[pt:],Yib[pt:],color=colors[i],transform=ccrs.PlateCarree(),label=b)
    i+=1
#     plt.text(Xib[0],Yib[0],b)
# plt.plot(Xis,Yis,'--',color='yellow',transform=ccrs.PlateCarree(),label='simulated ice drift') 
# gebco wms background 
service='https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?'
ax.add_wms(service,layers=['GEBCO_LATEST'],wms_kwargs={'width':900*2,'height':600*2})

feature=cpf.GSHHSFeature(scale='i',levels=[1],facecolor='#e6e1e1',alpha=1)
ax.add_feature(feature) 


# plt.legend()

plt.savefig('../generated_data/trial.pdf')
plt.close(fig) 
# plt.show() '#AAAAAA' #e6e1e1

C:\Users\vasulkar\AppData\Local\Continuum\anaconda3\lib\site-packages\cartopy\mpl\geoaxes.py:782: MatplotlibDeprecationWarning: Passing the minor parameter of set_xticks() positionally is deprecated since Matplotlib 3.2; the parameter will become keyword-only two minor releases later.
  return super(GeoAxes, self).set_xticks(xticks, minor)
C:\Users\vasulkar\AppData\Local\Continuum\anaconda3\lib\site-packages\cartopy\mpl\geoaxes.py:829: MatplotlibDeprecationWarning: Passing the minor parameter of set_yticks() positionally is deprecated since Matplotlib 3.2; the parameter will become keyword-only two minor releases later.
  return super(GeoAxes, self).set_yticks(yticks, minor)
C:\Users\vasulkar\AppData\Local\Continuum\anaconda3\lib\site-packages\owslib\map\wms111.py:127: UserWarning: Content metadata for layer "GEBCO_LATEST" already exists. Using child layer
  warnings.warn('Content metadata for layer "%s" already exists. Using child layer' % cm.id)
C:\Users\vasulkar\AppData\Local\Contin

In [50]:
yo=np.zeros(10);yo[0:6]=1;print(yo[6:]);print(yo)
y1=np.ones(4);y4=np.array([0,1])
y3=np.concatenate((y1,y4,yo));print(y3);print(np.shape(y3));print(y3[1:-2])
# Nk=np.ones(16);y3=y2+Nk;print(y3)

[0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
[1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
(16,)
[1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
